name: jaxGPT pipeline

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  check: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3 
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12.2'
      
      - name: 
        run: python -c "import sys; print(sys.version)"
     

  