name: jaxGPT pipeline

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  check: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3 
      - name: Set up Python 3.12
        with: 
          python-version:'3.12.2'
      
      - name: 
        runs-on: | 
          python -c "import sys; print(sys.version)"
      - name: 
        runs-on: |
          cd .github/workflows/scripts && python check_notebooks.py
      - name: 


  
